config/routes.rb
Pinteresting::Application.routes.draw do
  resources :pins

  devise_for :users
  root "pins#index"

 
get "about" => "pages#about" #Creates about_path
get "team" => "pages#team" #Creates team path
get "todo" => "pages#todo" #mytodolist, not database'd yet
get "dbase" => "pages#dbase"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
     Paperclip.options[:command_path] = 'C:/Program Files/ImageMagick-6.8.8-Q16'
     belongs_to :user
     has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
       validates :image, presence: true
  validates :description, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :pins

 validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end


  def about
  end

  def team
  end

 def todo
 end

def dbase
end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]


  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 6)

  end

 def dbase
    @pins = Pin.all
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
 

  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>

    </button>
    <%= link_to "Pinteresting", root_path, class:"navbar-brand" %>
  
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse navbar-ex1-collapse">
  
        <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li>
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> New Pin
            <% end %>
                </li>


              <% end %>
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "About", about_path %></li>
              <li><%= link_to "Team", team_path %></li>
          
<%# IF USER SIGNED IN...%>
              <% if user_signed_in? %>
          
  

                <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Sign In", new_user_session_path %></li>
              <% end %>
              <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->



</nav>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>



     <%= render 'layouts/header' %>


	<div class="container">
			<% flash.each do |name, msg| %>
    			<%= content_tag(:div, msg, class: "alert alert-info") %>
    			
			<% end %>
		<%= yield %>
	</div>




</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
  <h1>Welcome to my app!</h1>
  <p>
    <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  </p>

</div>

app/views/pages/about.html.erb

<h1>About us</h1>
<p>We're working on our one month rails pinteresting app! This site looks <i>sharp!</i></p>

app/views/pages/dbase.html.erb
<h1>Showing the pins below</h1>

<table border = 1 cellpadding = 5px>
  <thead>
    <tr>
      <th>Image</th>
      <th>Id</th>
      <th>userid</th>
      <th>Email</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
      <th>Characters</th>
      <th>Output</th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= image_tag pin.image.url(:medium) %></td>
        <td><%= pin.id %></td>
        <td><%= pin.user_id %></td>
        <td><%= pin.user.email if pin.user %></td>
        <td><%= pin.description %></td>
        <td><%= link_to 'Show', pin %></td>

        <% if pin.user == current_user %>

        <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
        <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>

        <% end %>

        <td><%= pin.description.length %> characters </td>
 <td>edit_pin_path(pin): <%= edit_pin_path(pin) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<% if user_signed_in? %>
  <%= link_to 'New Pin', new_pin_path %>
<% end %>



</div>


<br><br><br><hr style="height:5px;border:none;color:#333;background-color:red;" />
<div class ="container">
<% 
=begin

**JUST SCREWING AROUND BELOW, STRING EXPERIMENTAL TABLE
%>

<% 
=end %>

<table border = 1 cellpadding = 5px>

<thead>
  <tr><th colspan=4><H1>THIS SHOULDN'T SHOW UPString experiment table</h1>
</th></tr>
     <tr> 
      <th>id</th>
      <th>edit_pin_path(pin)</th>
      <th>Characters</th>
      <th>pin, method: :delete</th>
    </tr>
</thead>

<tbody>
 <% @pins.each do |pin| %>
<tr>
  <td><%= pin.id %></td>
  <td><%= edit_pin_path(pin)  %></td>
  <td><%= edit_pin_path(pin).length  %></td>
  <td>destroy_pin_path(pin)  %></td>
  </tr>
<% end %>
</tr>
</tbody>
</table>

<li>New pin path: <%= new_pin_path %></li>
<li>Pin path for 1: <%= pin_path(1) %></li>
<li>Pin path for 2: <%= pin_path(2) %></li>
<li>Pin path for 1000: <%= pin_path(1000) %></li>
<li>The first pin: <%= Pin.first.description %></li>
<li>The last pin: <%= Pin.last.description %></li>
<li>The 6th pin: Gahh why no work: <%%= Pin[6].description %></li>
</div>


app/views/pages/home.html.erb
<div class="jumbotron center">
     <h1>Welcome to my app!</h1>
     <% if user_signed_in? %>
          Welcome to members area, pal

<div>
     <%= link_to "View Pins", pins_path, class: "btn btn-default btn-lg" %>
     <%= link_to 'Create Pin', new_pin_path, class: "btn btn-primary btn-lg" %>
</div>

     <% else %>


<%#IF USER IS NOT LOGGED IN...%>
       <p>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
       </p>
  <% end %>  
</div>

app/views/pages/team.html.erb
<h1>Bogus team for now</h1>
<p>There'd be a whole lotta team info here...if there was a team! (...or a product for that matter!) </p>

app/views/pages/todo.html.erb

<div class="jumbotron">
     <h1>Todo list</h1>
     <% if user_signed_in? %>
       Welcome to members area, pal. Here's stuff on the todo list:
       <br>
<div>       
<u><strong>Here's what I want to eventually figure out:</strong></u>
<li>Trying to edit a URL from a non-logged in account (incognito) causes an error</li>
<li> <s>Turn this todo list of bullet points into its own page ~/todo</s></li>
<li>++Step it up and be able to strike out these to do items w/ checkboxes (THIS IS POSSIBLE W/ SCAFFOLDING! Each todo item has an id and is a record/row in db!)</li>
<li> How to call an individual pin, ex pin(1) and then have it display in the table <%= link_to "here", pins_path %></li>
<li> <s>How to make top row span/merge + center in the table <%= link_to "here", pins_path %></s></li>
<li> How to style tables & such with bootstrap? Highlight rows w/ mouseover, sort, etc</li>
<li> How can I use these skills to help Jeff?</li>
<li> Fix my edit to _form.html.erb where the button has create pin hard-coded into it</li>
<Li> For above, what I changed in ~/app/views/pins/_form.html.erb <strong>f.submit "Create Pin", class: "btn btn-primary"</strong> and changed to <Strong> f.button :submit, class: "btn btn-primary"</strong>
<li> <s>Easy command line way to get the column names?</s>$rails console and then $Pin.column_names</li>
<Li> Logging in, figure out how to welcome user by email. Ex "welcome to members area, {EMAIL FROM DEVISE DATABASE}"
</div>


     <% else %>


<%#IF USER IS NOT LOGGED IN...%>
 <p>
 <div border = 22>
 Psst...Log in to see the todo list</div>
 <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
 </p>
  <% end %>  
</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>

  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
</div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <%= pin.description %><br/>
        <strong><%= pin.user.name if pin.user %></strong>
        

        <% if pin.user == current_user %>
          <div class="actions">
           <%= link_to edit_pin_path(pin) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
            <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>
          </div>
          
        <% end %>
     



      </div>
    </div>
  <% end %>
</div>
<div class="center">
   <%= will_paginate @collection, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <%= image_tag @pin.image.url(:medium) %>
      </div>
      <div class="panel-body">
        <p><%= @pin.description %></p>
        <p><strong><%= @pin.user.name if @pin.user %></strong></p>

        <% if @pin.user == current_user %>
         <%= link_to edit_pin_path(@pin) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
            <%= link_to @pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>
        <% end %>

      </div>
    </div>
  </div>
</div>